{% set version = "1.0.13" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-pagoda2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pagoda2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pagoda2/pagoda2_{{ version }}.tar.gz
  sha256: cf9523409ac0bb8975d4abfa290e9acee788d4df720b58b4c0999e88f0e7a530

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - _openmp_mutex  # [linux]
    - llvm-openmp    # [osx]
    - libblas
    - liblapack
    - r-base
    - r-mass
    - r-matrix
    - r-n2r
    - r-r.utils
    - r-r6
    - r-rmtstat
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppeigen
    - r-rcppprogress
    - r-rook
    - r-rtsne
    - r-dendsort
    - r-drat
    - r-fastcluster
    - r-igraph
    - r-irlba
    - r-magrittr
    - r-mgcv
    - r-plyr
    - r-rjson
    - r-rlang
    - r-sccore >=0.1.1
    - r-urltools
  run:
    - _openmp_mutex  # [linux]
    - llvm-openmp    # [osx]
    - libblas
    - liblapack
    - r-base
    - r-mass
    - r-matrix
    - r-n2r
    - r-r.utils
    - r-r6
    - r-rmtstat
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppeigen
    - r-rcppprogress
    - r-rook
    - r-rtsne
    - r-dendsort
    - r-drat
    - r-fastcluster
    - r-igraph
    - r-irlba
    - r-magrittr
    - r-mgcv
    - r-plyr
    - r-rjson
    - r-rlang
    - r-sccore >=0.1.1
    - r-urltools

test:
  commands:
    - $R -e "library('pagoda2')"           # [not win]
    - "\"%R%\" -e \"library('pagoda2')\""  # [win]

about:
  home: https://github.com/kharchenkolab/pagoda2
  license: GPL-3.0-only
  summary: Analyzing and interactively exploring large-scale single-cell RNA-seq datasets. 'pagoda2' primarily performs normalization and differential gene expression analysis, with an interactive application for exploring single-cell RNA-seq datasets. It performs basic tasks such as cell size normalization, gene variance
    normalization, and can be used to identify subpopulations and run differential expression within individual samples. 'pagoda2' was written to rapidly process modern large-scale scRNAseq datasets of approximately 1e6 cells. The companion web application allows users to explore which gene expression patterns form the different
    subpopulations within your data. The package also serves as the primary method for preprocessing data for conos, <https://github.com/kharchenkolab/conos>. This package interacts with data available through the 'p2data' package, which is available in a 'drat' repository. To access this data package, see the instructions
    at <https://github.com/kharchenkolab/pagoda2>. The size of the 'p2data' package is approximately 6 MB.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
